version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - apps/server/.env
    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "5173:4173"
    depends_on:
      - server

  postgres:
    image: postgres:15
    restart: always
    ports:  
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: review-management
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
